Movie_info/urls.py
from django.urls import path

from . import views

app_name  = 'movie_info'

urlpatterns = [
    path('movie_list/', views.movie_list, name='list'),
    path('movie_list/<int:id>', views.movie_detail, name='detail'),
    path('', views.input_movie, name='input'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Movie_info.urls')),
]

Movie_info/models.py
from django.db import models

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django
django.setup()

# Create your models here.

# id, title, year, rating, genres, summary
class Movie_data_list(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    rating = models.FloatField(default=0.0)
    genres = models.CharField(max_length=255)
    summary = models.CharField(max_length=1500)


class Movie_review(models.Model):
    movie_id = models.ForeignKey(Movie_data_list, on_delete=models.CASCADE)
    review_id = models.BigAutoField(primary_key=True)
    text = models.CharField(max_length=1500)
    rating = models.IntegerField()

Movie_info/forms.py
from django import forms
from .models import Movie_data_list, Movie_review


class Input_new_form(forms.ModelForm):
    class Meta:
        model = Movie_data_list
        fields = ['title', 'year', 'genres', 'summary']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'year': forms.NumberInput(attrs={'class': 'form-control'}),
            'genres': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.TextInput(attrs={'class': 'form-control'}),
        }

        required = "__all__"


class Review_form(forms.ModelForm):
    class Meta:
        model = Movie_review
        fields = ['rating', 'text']
        widgets = {
            'rating': forms.Select(choices= ((str(x), x) for x in range(1,11)), attrs={'class':'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'rating':'평점',
            'text': '댓글내용',

        }
        required = "__all__"

Movie_info/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from .forms import *
from .filter import SortFilter
from django.views.generic.edit import CreateView

def movie_list(request):
    data = Movie_data_list.objects.all()

    filter = SortFilter(request.GET, queryset=data)
    data = filter.qs

    page = request.GET.get('page', '1')
    paginator = Paginator(data, 10)
    page_obj = paginator.get_page(page)

    context = {'data': page_obj, 'page': page, 'filter':filter}
    return render(request, 'Movie_info/movie_list.html', context)

def input_movie(request):
    if request.method == 'POST':
        form = Input_new_form(request.POST)
        if form.is_valid():
            data = form.save()
            return HttpResponseRedirect('movie_list/%i' % data.id)
    else:
        form = Input_new_form()
    context = {'form': form}
    return render(request, 'Movie_info/new_movie.html', context)

def movie_detail(request, id):
    data = Movie_data_list.objects.filter(id=id)
    review = Movie_review.objects.filter(movie_id=id)

    for i in review:
        if request.method == 'POST' and f'delete {i.review_id}' in request.POST:
            data = Movie_review.objects.get(review_id=i.review_id)
            print(i.review_id)
            data.delete()
            return HttpResponseRedirect(request.path_info)

    if request.method == 'POST':
        form = Review_form(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.movie_id = Movie_data_list.objects.get(id=id)
            f.save()
            return HttpResponseRedirect('%i' % id)
    else:
        form = Review_form()

    context = {'data': data, 'review': review, 'form':form}
    return render(request, 'Movie_info/movie_detail.html', context)

templates/Movie_info/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1>영화 상세조회</h1>
    <hr>

    <div class="container row">
      {% if data%}
      {% for i in data%}
        <dl class="row">
          <dt class="col-sm-3"><h3>TITLE</h3></dt>
          <dd class="col-sm-9"><h3>{{i.title}} ({{i.id}})</h3></dd>

          <dt class="col-sm-3">YEAR</dt>
          <dd class="col-sm-9">{{i.year}}</dd>

          <dt class="col-sm-3">RATING</dt>
          <dd class="col-sm-9">{{i.rating}}</dd>

          <dt class="col-sm-3">GENRES</dt>
          <dd class="col-sm-9">{{i.genres}}</dd>

          <dt class="col-sm-3 text-truncate">SUMMARY</dt>
          <dd class="col-sm-9">{{i.summary}}</dd>
        </dl>

      {% endfor %}
      {% endif %}

        <div class="container ">
                <br><br>
            <h2>Comments</h2>
            {% if review %}
                {% for c in review %}
                    <strong>
                        id: {{ c.review_id }}
                        score: {{ c.rating }}
                    </strong>
                    <br>
                    contents: {{c.text|truncatechars:30}}
                <br><br>
                <div>
                    <form action='' method="post">
                        {% csrf_token %}
                        <button type="submit" name="delete {{c.review_id}}" onclick="return confirm('정말 삭제하시겠습니까?');" class="">Delete</button>
                    </form>
                </div>
                <br><br>
                {%endfor%}
            {%endif%}
        </div>
        <div class="container my-3">
        <h1>새 리뷰 추가</h1>
        <hr>
        <div class="container">
            <form method="post" class="post-form my-3">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">저장</button>
            </form>
        </div>
    </div>
    <br><br>
    </div>

  <div class="text-right">
      <a href="{% url 'movie_info:list' %}" class="btn btn-primary">목록</a>
  </div>
</div>
{% endblock %}

templates/Movie_info/movie_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h1>영화 조회 API</h1>
    <hr>
    <div class="row">
        <form action="" method="get" name="filtering">
            {{filter.form}}
            <button class="btn btn-primary" type="submit">필터링</button>
        </form>
    </div>
    <br>
    <div class="row">
        <table class="table">
            <thead>
                <tr class="thead-dark">
                    <th>id</th>
                    <th>title</th>
                    <th>year</th>
                    <th>rate</th>
                    <th>genres</th>
                    <th>summary</th>
                </tr>
            </thead>
            <tbody>
                {% if data %}
                    {% for i in data %}
                        <tr>
                            <td>{{i.id}}</td>
                            <td>
                                <a href="{% url 'movie_info:detail' i.id %}">{{i.title|truncatechars:30}}</a>
                            </td>
                            <td>{{i.year}}</td>
                            <td>{{i.rating}}</td>
                            <td>{{i.genres}}</td>
                            <td>{{i.summary|truncatechars:40}}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="3">현재 영화 정보 없습니다.</td>
                    </tr>
                {%endif%}
            </tbody>
        </table>
        <ul class="pagination justify-content-center">
            {% if data.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            {% for page_number in data.paginator.page_range %}
            {% if page_number == data.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if data.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>

{% endblock %}

templates/Movie_info/new_movie.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h1>새 영화 추가</h1>
    <hr>
    <div class="container">
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">저장</button>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>영화 정보 조회</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="/">Movie_info API</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/">새 영화 추가</a></li>
            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/movie_list">영화 목록</a></li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>